"use client";

import "bootstrap/dist/css/bootstrap.css";
import "/style/globals.css";
import "/style/style.css";
import "/style/common.css";

import Navbar from "@/components/Navbar";
import TopHeader from "@/components/TopHeader";

import { Inter } from "next/font/google";
import Head from "next/head";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>Beraterstar</title>
        <link rel="stylesheet" href="/public/styles.css" />
        <link rel="stylesheet" href="/css/responsive.css" />
      </Head>

      <body>
        <TopHeader />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
